DROP TABLE IF EXISTS SJD_QUESTION_BANK;

CREATE TABLE `SJD_QUESTION_BANK` (
  `ID`   INT(11)  UNSIGNED        NOT NULL                COMMENT '题目ID',
  /*
  `KL_POINT1` INT(11)   UNSIGNED  NOT NULL       COMMENT '知识点1的ID',
  `KL_POINT2` INT(11)   UNSIGNED                  COMMENT '知识点2的ID',
  `KL_POINT3` INT(11)   UNSIGNED                  COMMENT '知识点3的ID',
  */
  `Q_TYPE`     TINYINT(1)  NOT NULL DEFAULT '0'      COMMENT '题目类型', -- 0为选择，1为填空
  `CREATE_TIME`  DATE  NOT NULL DEFAULT'2018-03-13'  COMMENT '创建时间',
  `USAGE_COUNT`       INT(11)    NOT NULL DEFAULT'0'     COMMENT '使用次数',
  `FIRST_ACCURACY`    FLOAT(4,2)    DEFAULT'0.0'             COMMENT '首次正确率', -- 记录用户首次答题的正确率
  `AVERAGE_ACCURACY`  FLOAT(4,2)    DEFAULT'0.0'             COMMENT '平均正确率',
  `IF_UNDER_VERIFY`   TINYINT(1)    NOT NULL  DEFAULT '1'    COMMENT '是否待审核',-- 0待审核，1已审核
  `AVERAGE_SPEED`      TINYINT(3)   NOT NULL  DEFAULT '0'    COMMENT '平均答题速度', -- 按秒就算
  `SCORE`              TINYINT(1)   DEFAULT'1'                COMMENT '分值',
  PRIMARY KEY (`ID`)
  /*
  CONSTRAINT FK_QUESTION_KNOWLEDGE1_ID FOREIGN KEY (`KL_POINT1`) REFERENCES SJD_KNOWLEDGE(`ID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  CONSTRAINT FK_QUESTION_KNOWLEDGE2_ID FOREIGN KEY (`KL_POINT2`) REFERENCES SJD_KNOWLEDGE(`ID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  CONSTRAINT FK_QUESTION_KNOWLEDGE3_ID FOREIGN KEY (`KL_POINT3`) REFERENCES SJD_KNOWLEDGE(`ID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE
  */
)ENGINE=InnoDB  DEFAULT CHARSET = utf8                    COMMENT '题库表';

-- INSERT INTO SJD_QUESTION_BANK VALUE (1, 0, '2018-03-15', 0, 0, 0, 1, 0, 0);

DELETE FROM SJD_QUESTION_BANK WHERE ID = 1;

DROP TABLE IF EXISTS SJD_MULTI_CHOICE;

CREATE TABLE SJD_MULTI_CHOICE(
  `QID` INT(11) UNSIGNED NOT NULL COMMENT '题目ID',
  `QUESTION`    VARCHAR(300) NOT NULL COMMENT '题干',
  `SELECTION_A` VARCHAR(140) NOT NULL COMMENT 'A选项信息',
  `SELECTION_B` VARCHAR(140) NOT NULL COMMENT 'B选项信息',
  `SELECTION_C` VARCHAR(140)           COMMENT 'C选项信息',
  `SELECTION_D` VARCHAR(140)           COMMENT 'D选项信息',
  `SELECTION_E` VARCHAR(140)           COMMENT 'E选项信息',
  `SELECTION_F` VARCHAR(140)           COMMENT 'F选项信息',
  `ANSWER`       TINYINT(1)   NOT NULL COMMENT '答案',
  PRIMARY KEY (`QID`)
  /*
  CONSTRAINT FK_MULTI_CHOICE_QUESTION_ID FOREIGN KEY (`QID`) REFERENCES SJD_QUESTION_BANK(`ID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE*/
)ENGINE=InnoDB  DEFAULT CHARSET = utf8                    COMMENT '选择题表';